### PR TITLE
Improve handling of default Configurator values

### PR DESCRIPTION
**Pull request by wasdennnoch**
Previously, default Configurator values had to explicitly set using `@ConfiguratorDefault()` - which only supported String values. Any value that was not provided in the environment was sorcefully set to `null`. This broke support for certain scenarios. Say you have a boolean value which should default to `true`, and it should be optional so that users aren't forced to add it to their environment. This couldn't be implemented before, as by default, if no environment value was set, the Configurator would forcefully set the field to `null`, causing an NPE as a `boolean` can't be null.

This change removes the `@ConfiguratorDefault` annotation outright in favor of explicitly setting defalt values, like
```java
public static long SOME_VALUE = -1;
```
Additionally, when a value is not provided in the environment, it will not be forced to `null` anymore; instead, its default value will be kept as is, or an exception will be thrown if the field is marked as required.

Lastly, you may not want certain field values containing secrets to show up in the logs, so I've added an API to avoid logging the values of certain fields during startup. It can be used like (Kotlin example):
```kt
Configurator.addRedactedField(TeaConfig::TEA_DISCORD_TOKEN.javaField)
```

### CODE REVIEW

**Review by ShindouMihou — APPROVED** [review]

**Comment by ShindouMihou** [comment]
You could probably just use another annotation for the redacted fields instead.

```java
@Redacted
public static String DISCORD_TOKEN;
```

Additionally, I wonder if we can reuse the annotation to be used in SLF4J to auto-redact the field as well in any logs.

**Comment by wasdennnoch** [comment]
Well that would make way too much sense.

I did investigate how to postprocess/redact Log4j logs but didn't find much and what I found didn't work so I scrapped that idea. There's probably some way but idk if it's worth the effort, given this is primarily aimed at the token which we log nowhere else anyways.

**Comment by ShindouMihou** [comment]
> Well that would make way too much sense.
> 
> I did investigate how to postprocess/redact Log4j logs but didn't find much and what I found didn't work so I scrapped that idea. There's probably some way but idk if it's worth the effort, given this is primarily aimed at the token which we log nowhere else anyways.

Yeah, we don't use it here that much, but we can relook into it later. A particular use-case we can do Redacted in is actually to redact critical variables from being logged in `eval`, I wonder if we can do that by checking if the output of the `eval` contains any of the redacted fields and redacting it?

This would be helpful in preventing a potential security risk if ever, in a crazily weird situation, one of the eval permitted users gets hacked. Although I'm sure you all have taken measures against it already.

**Comment by wasdennnoch** [comment]
> A particular use-case we can do Redacted in is actually to redact critical variables from being logged in eval, I wonder if we can do that by checking if the output of the eval contains any of the redacted fields and redacting it?
>
> This would be helpful in preventing a potential security risk if ever, in a crazily weird situation, one of the eval permitted users gets hacked.

Well, if someone has eval acces they can just log the token to discord directly (since they can't even see the logs), or do a `token.reverse()` or insert a random space somewhere to circumvent the entire detection, so I don't think this case applies here.

**Comment by ShindouMihou** [comment]
> > A particular use-case we can do Redacted in is actually to redact critical variables from being logged in eval, I wonder if we can do that by checking if the output of the eval contains any of the redacted fields and redacting it?
> > This would be helpful in preventing a potential security risk if ever, in a crazily weird situation, one of the eval permitted users gets hacked.
> 
> Well, if someone has eval acces they can just log the token to discord directly (since they can't even see the logs), or do a `token.reverse()` or insert a random space somewhere to circumvent the entire detection, so I don't think this case applies here.

Yeah, that's actually a take that I wasn't thinking about. Anyhow, this is good enough for now. If ever we need something more then we can just go implement it in the further future  anyway.

**Pull request merged**
